
export const ACTIONS = {
  CREATE_NEW_STUDENT: 'CREATE_NEW_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  FETCH_STUDENT_DATA: 'FETCH_STUDENT_DATA',
  FETCH_STUDENT_BY_ID: 'FETCH_STUDENT_BY_ID',
  FETCH_STUDENT_UPDATE: 'FETCH_STUDENT_BY_ID',
  FETCH_CITY_DATA: 'FETCH_CITY_DATA',
};


