@baseUrl = http://js-post-api.herokuapp.com/api
@student_id = lea11ziflg8xoiza
# Students
# 
# @name getAllStudents
GET {{baseUrl}}/students?_page=2&_limit=10
###
# @name getStudentById
GET {{baseUrl}}/students/{{student_id}}
###
# @name addNewStudent
POST {{baseUrl}}/students
Content-Type: application/json

{
    "name": "new one",
    "age": 27,
    "mark": 9.5,
    "gender": "Male",
    "city": "pt"
}
###
# @name updateStudent
PATCH {{baseUrl}}/students/{{student_id}}
Content-Type: application/json

{
    "name": "Testttt"
}
###
# @name removeStudent
DELETE {{baseUrl}}/students/{{student_id}}